name: toon_dart_generator
description: Code generator for TOON format serialization in Flutter/Dart
version: 1.0.0
homepage: https://toonformat.dev
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.5.0
  toon_formater:
    path: ../toon_formater

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^1.7.0
  test: ^1.24.0

