name: toon_formater
description: Token-Oriented Object Notation (TOON) â€“ A compact, deterministic JSON format for LLM prompts (Dart implementation)
version: 1.0.0
homepage: https://toonformat.dev
repository: https://github.com/toon-format/toon

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

